version: '3.8'

services:
  app:
    build: .
    container_name: tradeapp
    volumes:
      - ./data:/app/data  # Mount data folder
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
      - "127.0.0.1:53:53/udp"
    restart: always


networks:
  default:
    external:
      name: app-network